branch-defaults:
  default:
    environment: Projectalpha
environment-defaults:
  Projectalpha:
    branch: null
    repository: null
global:
  application_name: Project_1
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 2.7 running
    on 64bit Amazon Linux/2.6.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
